// Generated by Supabase MCP `generate_typescript_types` against project
// zxfsqprzoremabtgqfer. Regenerate via:
//
//   npx supabase gen types typescript --project-id zxfsqprzoremabtgqfer > apps/web/lib/supabase/database.types.ts
//
// (or call the MCP tool from Claude Code).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      hadith_table: {
        Row: {
          arabicBabName: string | null;
          arabicBabNumber: string | null;
          arabicgrade1: string;
          arabicText: string | null;
          arabicURN: number;
          babID: number;
          bookNumber: string;
          collection: string;
          englishBabName: string | null;
          englishBabNumber: string | null;
          englishgrade1: string;
          englishText: string | null;
          englishURN: number;
          hadithNumber: string;
          last_updated: string | null;
          ourHadithNumber: number;
          xrefs: string;
        };
        Insert: {
          arabicBabName?: string | null;
          arabicBabNumber?: string | null;
          arabicgrade1: string;
          arabicText?: string | null;
          arabicURN: number;
          babID: number;
          bookNumber: string;
          collection: string;
          englishBabName?: string | null;
          englishBabNumber?: string | null;
          englishgrade1: string;
          englishText?: string | null;
          englishURN: number;
          hadithNumber: string;
          last_updated?: string | null;
          ourHadithNumber: number;
          xrefs: string;
        };
        Update: {
          arabicBabName?: string | null;
          arabicBabNumber?: string | null;
          arabicgrade1?: string;
          arabicText?: string | null;
          arabicURN?: number;
          babID?: number;
          bookNumber?: string;
          collection?: string;
          englishBabName?: string | null;
          englishBabNumber?: string | null;
          englishgrade1?: string;
          englishText?: string | null;
          englishURN?: number;
          hadithNumber?: string;
          last_updated?: string | null;
          ourHadithNumber?: number;
          xrefs?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      get_books_for_collection: {
        Args: { p_collection: string };
        Returns: {
          book_name_en: string;
          book_number: number;
          hadith_count: number;
        }[];
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]),
> = (DefaultSchema["Tables"] & DefaultSchema["Views"])[T] extends { Row: infer R } ? R : never;

export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Insert: infer I } ? I : never;

export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Update: infer U } ? U : never;

export const Constants = {
  public: { Enums: {} },
} as const;
