-- Add Urdu translation columns to hadith_table.
--
-- Populated out-of-band by scraper/populate_urdu.mjs (matches scraped Arabic
-- against the Arabic already in this table, by (collection, hadithNumber)).
-- Purely additive: existing columns/rows are untouched; rows with no Urdu match
-- keep these as NULL.
--
-- NOTE: 0003_hadith_table_raw.sql is auto-generated by scripts/convert_hadith_dump.py,
-- so the Urdu columns live here in a separate migration instead of being edited into it.

alter table public.hadith_table
  add column if not exists "urduText"  text,
  add column if not exists "urduSanad" text;
